/**
 * Screenshots, keyed by WHAT THEY ARE OF rather than by when they were taken.
 *
 *   const shots = createShots({ dir: paths.shots });
 *   await shots.take(page, 'payers/editor', { note: 'editor drawer open on a mapped payer' });
 *   await shots.take(page, 'payers/row-actions', { of: page.locator('.row-actions') });
 *
 * FRESHEST WINS. One file per key, overwritten every capture. There is no baseline and no diff,
 * deliberately: these are documentation — the thing you paste into a PR so a design review can be
 * visual — not regression baselines. A baseline set demands curation, goes stale silently, and
 * turns every intentional redesign into a wall of red. If you ever want pixel regression, that is a
 * different tool with a different lifecycle; do not grow it out of this one.
 *
 * That is also why the key matters more than the filename. `payers/editor` is a claim about which
 * view this is, so the next capture of the same view REPLACES it instead of piling up
 * `editor-2.png`, `editor-final.png`, `editor-final-2.png` next to a stale original nobody dares
 * delete.
 *
 * Every capture also rewrites the catalogue (`index.json` + `INDEX.md`), so the directory can
 * always answer "what is in here and what is it of" without opening a single png. A shot with no
 * `note` is a png whose meaning lives only in the head of whoever took it.
 */
const fs = require('fs');
const path = require('path');

/** `Payers / Editor Drawer` -> `payers/editor-drawer`. Segments survive; everything else slugs. */
const slugKey = (key) =>
  String(key)
    .split('/')
    .map((seg) => seg.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''))
    .filter(Boolean)
    .join('/');

/**
 * @param {object} opts
 * @param {string} opts.dir            where shots live
 * @param {string[]} [opts.mask]       selectors to paint over — the project supplies these; there
 *                                     is no useful default, since only the project knows what its
 *                                     sensitive regions are
 * @param {string} [opts.env]          environment label, recorded so a shot of production is
 *                                     identifiable as one later
 */
const createShots = ({ dir, mask = [], env = process.env.E2E_ENV || 'local' }) => {
  const indexFile = path.join(dir, 'index.json');

  const readIndex = () => {
    try {
      return JSON.parse(fs.readFileSync(indexFile, 'utf8'));
    } catch {
      return {}; // absent or hand-mangled — a catalogue is not worth failing a run over
    }
  };

  const writeIndex = (index) => {
    fs.writeFileSync(indexFile, `${JSON.stringify(index, null, 2)}\n`);
    const rows = Object.entries(index).sort(([a], [b]) => a.localeCompare(b));
    fs.writeFileSync(
      path.join(dir, 'INDEX.md'),
      [
        '# Shots',
        '',
        'Generated by `core/shots.js` — freshest capture of each view wins. Do not hand-edit.',
        '',
        '| view | file | what it shows | captured |',
        '| --- | --- | --- | --- |',
        ...rows.map(
          ([key, e]) =>
            `| \`${key}\` | ${e.file} | ${e.note || '—'}${e.masked ? ' _(masked)_' : ''} | ${e.capturedAt} |`,
        ),
        '',
      ].join('\n'),
    );
  };

  return {
    /**
     * @param {import('playwright').Page} page
     * @param {string} key         what this is a shot OF — the identity, not a filename
     * @param {object} [opts]
     * @param {object} [opts.of]   a Locator to shoot instead of the page (an element shot)
     * @param {boolean} [opts.full] full scrollable page rather than the viewport. Off by default
     *   for a measured reason: a full-page shot of a list that renders every row came out
     *   1600x109241 — a file no human opens and no diff can use. The viewport is what a person
     *   actually sees. Pass it deliberately, for a short page you want whole.
     * @param {string} [opts.note] one line: what a reader is looking at
     */
    async take(page, key, { of = null, full = false, note = '' } = {}) {
      const slug = slugKey(key);
      if (!slug) throw new Error(`shots.take: key ${JSON.stringify(key)} slugs to nothing`);

      const file = `${slug}.png`;
      const target = path.join(dir, file);
      fs.mkdirSync(path.dirname(target), { recursive: true });

      const masked = mask.length > 0 && !of; // Locator.screenshot() takes no mask
      await (of || page).screenshot({
        path: target,
        ...(of ? {} : { fullPage: full }),
        ...(masked ? { mask: mask.map((sel) => page.locator(sel)), maskColor: '#111827' } : {}),
      });

      const index = readIndex();
      index[slug] = {
        file,
        note,
        url: page.url(),
        env,
        element: of ? String(of) : undefined,
        masked,
        capturedAt: new Date().toISOString(),
      };
      writeIndex(index);

      return {
        path: target,
        masked,
        // A shot leaving this machine — into a ticket, a PR, a chat, an agent transcript — is a
        // disclosure, not a local file. No default can decide that for you, so say it plainly.
        warning:
          !masked && env !== 'local'
            ? `unmasked ${env} shot — local only unless you have checked what is in it`
            : '',
      };
    },

    /** The catalogue, for a caller that wants to assert on it. */
    catalogue: readIndex,
  };
};

module.exports = { createShots, slugKey };
