#!/usr/bin/env python3
"""
Write the table the plugin picks barks from: data/F4SE/Plugins/Rapport/barks.json.

    python scripts/build-barks-table.py           # write it
    python scripts/build-barks-table.py --check   # fail if the committed table is stale

The plugin chooses the line - by persona, scenario, role and speaker sex - and
the bridge calls Say on that line's Topic. So the plugin needs, for every line,
the Topic's FILE-RELATIVE form id: the load-order byte masked off, because the
bridge resolves it with Game.GetFormFromFile(id, "Rapport.esp"). A runtime id
(E2xxxxxx on the development machine) would work there and nowhere else.

The ids come from make_dialogue.load() - the SAME function that numbers the ESP -
so this table cannot name a Topic the plugin does not have, provided both were
built from the same bank. --check is what proves they were.

PERSONA ORDER IS A SAVE-FACING CONSTANT. The plugin derives an NPC's persona from
their form id as an index into this list (R-7). Reorder it and every NPC in every
existing save silently changes character. It is written from PERSONA_ORDER below,
never from the bank's dict order, and a persona added later goes on the END.
"""
import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import make_dialogue  # noqa: E402

OUT = ROOT / "data/F4SE/Plugins/Rapport/barks.json"

# Append-only, for the reason in the docstring.
PERSONA_ORDER = ["mercantile", "romantic", "vulgar", "reticent"]


def table():
    bank = json.loads((ROOT / "voice/lines.json").read_text(encoding="utf-8"))
    if set(bank["personas"]) != set(PERSONA_ORDER):
        sys.exit(f"bank personas {sorted(bank['personas'])} != PERSONA_ORDER {PERSONA_ORDER} - "
                 f"a new persona goes on the END of PERSONA_ORDER, never in the middle")

    lines = []
    for ln, _info, topic in make_dialogue.load():
        entry = {
            "id": ln["id"],
            "kind": ln["kind"],
            "persona": ln["persona"],
            # File-relative: GetFormFromFile adds the load-order byte back.
            "topic": topic & 0x00FFFFFF,
        }
        if ln["kind"] == "pair":
            entry["scenario"] = ln["scenario"]
            entry["role"] = ln["role"]
        else:
            entry["audience"] = ln["audience"]
        if "gender" in ln:
            entry["gender"] = ln["gender"]
        lines.append(entry)

    return {
        "_": "GENERATED by scripts/build-barks-table.py from voice/lines.json and "
             "voice/formids.json. Do not edit the lines by hand; the settings above them are yours.",
        "enabled": True,
        # The responder answers after the initiator's line, not over it. Most pair
        # lines run 3-4 seconds; the bridge polls every PollSeconds, so the real
        # gap is this rounded up to the next poll.
        "responderDelaySeconds": 4.5,
        # R-12 bystanders. Chance is per watcher per scene (one roll, when they
        # first both stand near AND see it); the rest keep lines from colliding.
        "observers": {"enabled": True, "radius": 900, "chance": 0.33, "startAfterSeconds": 10,
                      "gapSeconds": 6, "cooldownSeconds": 300},
        "plugin": make_dialogue.PLUGIN,
        "personas": PERSONA_ORDER,
        "lines": lines,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    fresh = table()
    if OUT.exists():
        old = json.loads(OUT.read_text(encoding="utf-8"))
        # The settings are the owner's to tune; only the generated half must match.
        for key in ("enabled", "responderDelaySeconds", "observers"):
            fresh[key] = old.get(key, fresh[key])
    text = json.dumps(fresh, indent=1) + "\n"

    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is STALE - run scripts/build-barks-table.py")
            return 1
        print(f"barks table current: {len(fresh['lines'])} lines")
        return 0

    OUT.write_text(text, encoding="utf-8")
    kinds = {}
    for ln in fresh["lines"]:
        kinds[ln["kind"]] = kinds.get(ln["kind"], 0) + 1
    print(f"wrote {OUT.relative_to(ROOT)}: {len(fresh['lines'])} lines {kinds}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
