#!/usr/bin/env python3
"""
Step 5 of the voice fallback (V-25): write the table the Voices service reads,
data/F4SE/Plugins/Rapport/voices.json.

    python scripts/build-voices-table.py           # write it
    python scripts/build-voices-table.py --check   # fail if the committed table is stale

Inputs, all committed: voice/fallback/map.json (the measured map, from
scripts/voice-similarity.py) and voice/fallback/overrides.json (the OWNER'S
decisions, which win over any measurement).

THE PIPELINE, in order - each step's output is the next one's input:
    voice-inventory.py   which voice types exist, their recordings, VTYP flags
    voice-races.py       which races and sexes of NPC use each voice
    voice-similarity.py  fingerprints (.venv-voice) and the measured map
    build-voices-table   this: map + owner overrides -> the runtime table

OVERRIDES. {"NPCFPiper": "FemaleBoston"} makes Piper borrow FemaleBoston;
{"NPCFPiper": null} keeps her silent. The owner picks by ear (V-9); the
measurement only proposes. An override naming a voice we did not render, or a
child voice set to borrow anything, is refused rather than written.
"""
import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FB = ROOT / "voice/fallback"
OUT = ROOT / "data/F4SE/Plugins/Rapport/voices.json"

# Resolved in-game with LookupForm, so they are file-relative ids + their master.
SPEAKING_RACES = [
    {"race": "HumanRace", "master": "Fallout4.esm", "id": 0x013746},
    {"race": "GhoulRace", "master": "Fallout4.esm", "id": 0x0EAFB6},
]
UNMAPPED = {"female": "FemaleEvenToned", "male": "MaleEvenToned"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    mapping = json.loads((FB / "map.json").read_text(encoding="utf-8"))
    inventory = {r["edid"]: r for r in json.loads((FB / "inventory.json").read_text(encoding="utf-8"))} \
        if (FB / "inventory.json").exists() else None
    over_path = FB / "overrides.json"
    overrides = json.loads(over_path.read_text(encoding="utf-8")) if over_path.exists() else {}
    overrides = {k: v for k, v in overrides.items() if not k.startswith("_")}

    # Our 32, with ids. From the committed map's own records where possible, so
    # --check works in CI without the game's archives.
    own_path = FB / "own.json"
    if inventory is not None:
        own = sorted(({"voice": n, "master": r["master"], "id": r["id"]}
                      for n, r in inventory.items() if r["rendered"]), key=lambda x: x["voice"])
        own_path.write_text(json.dumps(own, indent=1) + "\n", encoding="utf-8")
    own = json.loads(own_path.read_text(encoding="utf-8"))
    own_by = {o["voice"]: o for o in own}

    errors, borrow = [], []
    for name, row in sorted(mapping.items()):
        as_voice = row["borrow"]
        if name in overrides:
            as_voice = overrides[name]
            if as_voice is not None and as_voice not in own_by:
                errors.append(f"override {name} -> {as_voice}: not a voice we rendered")
                continue
            if as_voice is not None and (row.get("silent") or "").startswith("child"):
                errors.append(f"override {name} -> {as_voice}: a CHILD voice never borrows")
                continue
        entry = {"voice": name, "master": row["master"], "id": row["id"]}
        if as_voice:
            entry["as"] = {"voice": as_voice, "master": own_by[as_voice]["master"], "id": own_by[as_voice]["id"]}
            if name not in overrides:
                entry["score"] = next((c["score"] for c in row["candidates"] if c["voice"] == as_voice), None)
            else:
                entry["owner"] = True
        else:
            # Recorded, so the runtime knows this silence is deliberate and does
            # not hand the voice the unmapped sex default instead.
            entry["as"] = None
            entry["why"] = "owner" if name in overrides else row.get("silent")
        borrow.append(entry)

    unknown = [k for k in overrides if k not in mapping]
    if unknown:
        errors.append(f"overrides name voices the map does not have: {unknown[:5]}")
    if errors:
        print("REFUSED:\n  " + "\n  ".join(errors))
        return 1

    table = {
        "_": "GENERATED by scripts/build-voices-table.py from voice/fallback/map.json and "
             "overrides.json. Change a pairing in overrides.json, not here.",
        "enabled": True,
        "own": [{"master": o["master"], "id": o["id"], "voice": o["voice"]} for o in own],
        "borrow": borrow,
        # For voice types the measurement never heard (a mod's). Only actors of
        # these races may take the sex default; anything else stays silent.
        "speakingRaces": SPEAKING_RACES,
        "unmapped": {sex: {"voice": v, "master": own_by[v]["master"], "id": own_by[v]["id"]}
                     for sex, v in UNMAPPED.items()},
    }
    text = json.dumps(table, indent=1) + "\n"
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is STALE - run scripts/build-voices-table.py")
            return 1
        print(f"voices table current: {len(own)} own, {len(borrow)} mapped")
        return 0
    OUT.write_text(text, encoding="utf-8")
    speaking = sum(1 for b in borrow if b["as"])
    print(f"wrote {OUT.relative_to(ROOT)}: {len(own)} own, {speaking} borrow, "
          f"{len(borrow) - speaking} silent, {sum(1 for b in borrow if b.get('owner'))} by owner")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
