<#
.SYNOPSIS
  Copies the built plugin and its data into the Vortex staging folder for this mod.

.DESCRIPTION
  Vortex owns Data/, so the dev build is installed as an ordinary Vortex mod rather
  than dropped loose into the game folder. Run this after a build; Vortex deploys by
  hardlink, so an existing deployment updates in place and needs no redeploy.

  Refuses to run while Vortex or the game is open: the first would half-write the
  staging folder, the second holds the DLL open so the copy silently does nothing.

  ASCII only, deliberately. This file gets run by Windows PowerShell 5.1 as well as
  pwsh 7, and 5.1 reads a BOM-less UTF-8 script as ANSI -- one em dash in a string
  was enough to turn it into a parse error that still exited 0.
#>
[CmdletBinding()]
param(
    [string] $Staging = 'D:\Vortex\fallout4\mods\Rapport-dev',
    [string] $Config  = 'Release'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

# The game is a hard stop: it holds the DLL open, so the copy would silently do
# nothing. Vortex is only a warning -- it is the normal working state, and a new
# file needs its Deploy button anyway.
$game = Get-Process -Name 'Fallout4' -ErrorAction SilentlyContinue
if ($game) {
    throw "Fallout4 is running (PID $($game.Id -join ', ')). Close it before deploying."
}

$vortex = Get-Process -Name 'Vortex' -ErrorAction SilentlyContinue

$dll = Join-Path $root "build\$Config\Rapport.dll"
if (-not (Test-Path $dll)) {
    throw "No build at $dll. Build first."
}

$plugins = Join-Path $Staging 'F4SE\Plugins'
New-Item -ItemType Directory -Force -Path (Join-Path $plugins 'Rapport') | Out-Null

Copy-Item $dll (Join-Path $plugins 'Rapport.dll') -Force
Copy-Item (Join-Path $root 'data\F4SE\Plugins\Rapport.ini') $plugins -Force

# The dev command channel, turned on HERE and nowhere else.
#
# The repo's ini ships with DevMailbox=0 and must keep doing so -- make-release
# copies that same file, so a 1 in it would put a command channel in strangers'
# games. Flipping it in the staging copy after the copy is the one place the
# distinction between "the dev build" and "the build" actually lives.
$devIni = Join-Path $plugins 'Rapport.ini'
(Get-Content $devIni) -replace '^DevMailbox=0', 'DevMailbox=1' | Set-Content $devIni -Encoding ASCII
Write-Host '  dev command channel: ON in staging (repo default stays 0)'
Copy-Item (Join-Path $root 'data\F4SE\Plugins\Rapport\*.json') (Join-Path $plugins 'Rapport') -Force

# The plugin and the compiled Papyrus. Both are built, not committed: the esp is
# generated by tools/make_esp.py and the pex by scripts/build-papyrus.ps1.
# AAF merges settings files by priority, so our overlay changes nothing in the
# AAF install itself and can be deleted at any time.
$aafOverlay = Join-Path $root 'data\AAF'
if (Test-Path $aafOverlay) {
    $aafTarget = Join-Path $Staging 'AAF'
    New-Item -ItemType Directory -Force -Path $aafTarget | Out-Null
    Copy-Item (Join-Path $aafOverlay '*.ini') $aafTarget -Force
    Copy-Item (Join-Path $aafOverlay '*.xml') $aafTarget -Force
}

# The overlay assets: the LooksMenu templates, their materials and the textures
# themselves. These are the only art Rapport ships, and they are GENERATED --
# run tools/make_overlays.py, not an image editor.
#
# Copied as whole trees rather than by extension like the AAF files above,
# because a .dds under Textures and a .bgem under Materials have to keep their
# folder structure: the material names the texture by path and the template
# names the material by path, so a flattened copy resolves to nothing and fails
# silently as an actor with no overlay on them.
foreach ($tree in @(
    @{ From = 'data\F4SE\Plugins\F4EE'; To = 'F4SE\Plugins\F4EE' },
    @{ From = 'data\Materials';           To = 'Materials' },
    @{ From = 'data\Textures';            To = 'Textures' },
    @{ From = 'data\MCM';                 To = 'MCM' })) {
    $src = Join-Path $root $tree.From
    if (Test-Path $src) {
        $dst = Join-Path $Staging $tree.To
        New-Item -ItemType Directory -Force -Path $dst | Out-Null
        Copy-Item (Join-Path $src '*') $dst -Recurse -Force
    } else {
        Write-Host "  WARNING: no $($tree.From) - run tools/make_overlays.py (sweat and flush will be missing)"
    }
}

$esp = Join-Path $root 'build\esp\Rapport.esp'

# The optional Moisturizer plugin. It is a separate esp for one reason: the
# script inside it names Commonwealth Moisturizer types, and a script that names
# a type nobody has installed is a reference the VM cannot resolve. Keeping it
# out of Rapport.esp means Rapport itself never carries that risk.
$espMoist = Join-Path $root 'build\esp\Rapport_Moisturizer.esp'
if (Test-Path $espMoist) { Copy-Item $espMoist $Staging -Force }
if (Test-Path $esp) {
    Copy-Item $esp $Staging -Force
} else {
    Write-Host "  WARNING: no Rapport.esp - run tools/make_esp.py"
}

$pex = Join-Path $root 'build\papyrus\Rapport'
if (Test-Path $pex) {
    $scripts = Join-Path $Staging 'Scripts\Rapport'
    New-Item -ItemType Directory -Force -Path $scripts | Out-Null
    Copy-Item (Join-Path $pex '*.pex') $scripts -Force
} else {
    Write-Host "  WARNING: no compiled scripts - run scripts/build-papyrus.ps1"
}

# Report what actually landed in both places. A deploy that silently did nothing
# looks exactly like a deploy that worked, so print the evidence.
foreach ($path in (Join-Path $plugins 'Rapport.dll'),
                  (Join-Path $Staging 'Rapport.esp'),
                  (Join-Path $Staging 'Scripts\Rapport\Bridge.pex'),
                  (Join-Path $Staging 'F4SE\Plugins\F4EE\Overlays\Rapport\overlays.json'),
                  (Join-Path $Staging 'Materials\Overlays\Rapport\Rapport_Sweat_2.bgem'),
                  (Join-Path $Staging 'Textures\Overlays\Rapport\Rapport_Sweat_2.dds'),
                  (Join-Path 'D:\GOGGames\Fallout 4 GOTY\Data\F4SE\Plugins' 'Rapport.dll')) {
    if (Test-Path $path) {
        $item = Get-Item $path
        Write-Host ("  {0}  {1} bytes  {2:HH:mm:ss}" -f $item.FullName, $item.Length, $item.LastWriteTime)
    } else {
        Write-Host "  MISSING: $path"
    }
}
if ($vortex) {
    Write-Host "Vortex is open. Existing files updated in place through their hardlinks; press Deploy if you added a new one."
}
Write-Host "Deployed. Launch through F4SE; the log is Documents\My Games\Fallout4\F4SE\Rapport.log"
