#!/usr/bin/env python3
"""
Which voice an NPC borrows for an addon's DIALOGUE lines (owner, 2026-09-25: "use our vocal
embeddings"). Overture's lines are recorded in fewer voices than Rapport's barks, so the bark map
(voice-similarity.py, nearest of all 32) can name a voice Overture has no file in. This is the same
measurement restricted to the voices the dialogue plugin actually ships.

    .venv-voice/Scripts/python scripts/voice-dialogue-map.py
    .venv-voice/Scripts/python scripts/voice-dialogue-map.py --targets FemaleBoston,MaleBoston,...

Reads voice/fallback/{embeddings.npz, inventory.json, map.json}; writes voice/fallback/dialogue-map.json,
which build-voices-table.py turns into the "dialogue" section of voices.json.

THE SAME HARD RULES as the bark map, taken from it rather than re-derived:
  - who may borrow at all: a voice the bark map lets borrow (eligible race, sex agreed by every
    witness, never a child's voice). A voice the bark map keeps silent stays silent here too;
  - same sex only;
  - the owner's overrides.json still wins, in build-voices-table.py.
A RENDERED voice (one of Rapport's 32) that the dialogue plugin does not ship borrows too: a Gunner
speaking Overture's lines has no file of their own either.
"""
import argparse
import json
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
FB = ROOT / "voice/fallback"

# Overture's voices (O-5's six core types, plus the five the owner funded on 2026-09-25).
DEFAULT_TARGETS = ["FemaleBoston", "FemaleEvenToned", "FemaleRough", "MaleBoston", "MaleEvenToned", "MaleRough",
                   "MaleGhoul", "MaleOld", "RaiderMale02", "FemaleGhoul", "DLC03TrapperMale01"]


def female_by_name(n):
    low = n.lower()
    return True if "female" in low else (False if "male" in low else None)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--targets", default=",".join(DEFAULT_TARGETS))
    a = ap.parse_args()
    targets = [t.strip() for t in a.targets.split(",") if t.strip()]

    z = np.load(FB / "embeddings.npz")
    names = [str(n) for n in z["names"]]
    vecs = z["vecs"]
    idx = {n: i for i, n in enumerate(names)}
    inv = {r["edid"]: r for r in json.loads((FB / "inventory.json").read_text(encoding="utf-8"))}
    bark = json.loads((FB / "map.json").read_text(encoding="utf-8"))
    races = json.loads((FB / "vt-races.json").read_text(encoding="utf-8"))
    child = {"HumanChildRace", "GhoulChildRace"}

    missing = [t for t in targets if t not in idx]
    if missing:
        raise SystemExit("no fingerprint for target voice(s): " + ", ".join(missing))
    sex_of = {t: female_by_name(t) for t in targets}
    if None in sex_of.values():
        raise SystemExit("a target's sex is not in its name: " + ", ".join(t for t, s in sex_of.items() if s is None))

    out, silent = {}, 0
    for n in names:
        if n in targets or n not in inv:
            continue
        row = inv[n]
        if row["rendered"]:
            # The bark map never judges our own 32 (they speak as themselves there), so its
            # children rule is applied here in code, not trusted to which voices we chose.
            if set(races.get(n, {}).get("races", {})) & child:
                silent += 1
                continue
            sex = female_by_name(n)
        else:
            entry = bark.get(n)
            if not entry or not entry.get("borrow"):
                silent += 1   # the bark map's hard rules said no
                continue
            sex = entry["female"]
        if sex is None:
            silent += 1
            continue
        same = [t for t in targets if sex_of[t] == sex]
        if not same:
            silent += 1   # no target of this sex: silence, never the other sex
            continue
        best = max(((float(vecs[idx[n]] @ vecs[idx[t]]), t) for t in same))
        out[n] = {"master": row["master"], "id": row["id"], "as": best[1], "score": round(best[0], 3)}

    (FB / "dialogue-map.json").write_text(json.dumps(
        {"_": "GENERATED by scripts/voice-dialogue-map.py. Nearest same-sex voice among the dialogue "
              "plugin's own, by fingerprint; the bark map's hard rules decide who may borrow at all.",
         "targets": targets, "borrow": out}, indent=1), encoding="utf-8")
    print(f"{len(out)} voices borrow for dialogue, {silent} stay silent, targets {len(targets)}")
    for n in ("NPCMMayorMcDonough", "NPCFPiper", "NPCMPrestonGarvey", "NPCFMagnolia", "GunnersMale01", "BoSFemale01"):
        if n in out:
            print(f"  {n:24s} -> {out[n]['as']:20s} {out[n]['score']}")


if __name__ == "__main__":
    main()
