#pragma once

#include "NamedLock.h"

namespace RP
{
	// Scene barks (R-9): when a scene starts, the two people in it say something
	// that fits the decision that produced it.
	//
	// This class only CHOOSES. The line is spoken by the bridge, which receives a
	// kSayTopic order and calls Say on the Papyrus side -- the plugin never calls
	// into the VM (rule 1). The table it chooses from is generated by
	// scripts/build-barks-table.py from the same bank that numbers the ESP, so a
	// line picked here is a Topic the plugin actually has.
	//
	// Who speaks when: the initiator on "scene started", the responder a beat
	// later so the two lines do not play over each other. Observers are R-12 and
	// are not here yet.
	class Barks
	{
	public:
		[[nodiscard]] static Barks& GetSingleton() noexcept;

		void Load();

		// Below PapyrusLink's stale-start guard, so a late AAF event for a released
		// request can never make somebody speak for a scene that is not theirs.
		void OnSceneStarted(
			std::int32_t a_request, std::uint32_t a_initiator, std::uint32_t a_responder,
			std::string_view a_scenario);

		// Every way a scene ends. A reply still waiting belongs to a scene that is
		// gone, and speaking it would be a line about nothing.
		void OnSceneEnded();

		// Every poll. Releases the responder's line once it is due.
		void Pump();

		// R-7: derived from the form id, never stored. The same NPC is the same
		// persona forever, on every machine, at zero save cost.
		[[nodiscard]] std::string_view PersonaOf(std::uint32_t a_formID) const;

		// The bank also holds OBSERVER lines (R-12). Watchers decides WHO speaks
		// and WHEN; this only says WHAT: a line for this persona, audience ("alone"
		// or "crowd") and sex. Returns the Topic's file-relative id (0 when nothing
		// fits, or barks are off) and the line id for the log.
		// a_heardOnly: the watcher heard it through a wall and did not see it, so
		// no line that talks about seeing ("look at that") is eligible.
		[[nodiscard]] std::pair<std::uint32_t, std::string> PickObserver(
			std::string_view a_persona, std::string_view a_audience, std::int32_t a_sex, bool a_heardOnly);

	private:
		struct Line
		{
			std::string   id;
			bool          observer{ false };
			std::string   persona;
			std::string   scenario;   // pair lines
			std::string   role;       // pair lines
			std::string   audience;   // observer lines
			bool          sight{ false };   // observer line that only makes sense if SEEN
			char          gender{ 0 };   // 'm', 'f', or 0 for either
			std::uint32_t topic{ 0 };    // FILE-RELATIVE; the bridge adds the load order
		};

		struct Reply
		{
			std::int32_t                          request{ 0 };
			std::uint32_t                         speaker{ 0 };
			std::uint32_t                         target{ 0 };
			std::uint32_t                         topic{ 0 };
			std::string                           id;
			std::chrono::steady_clock::time_point due{};
		};

		// Null when nothing fits -- which the generator's coverage check says
		// cannot happen for a known scenario, and which is logged if it does.
		[[nodiscard]] const Line* Pick(
			std::string_view a_persona, std::string_view a_scenario, std::string_view a_role,
			std::int32_t a_sex);

		// personas.json, read at the end of Load. Caller holds _lock.
		void LoadOverrides();

		// Shared by both pickers: a random line from the fits, never the one this
		// key played last time. Caller holds _lock.
		[[nodiscard]] const Line* Choose(std::vector<const Line*> a_fits, const std::string& a_key);

		mutable std::timed_mutex _lock;
		bool                     _enabled{ false };
		float                    _responderDelay{ 4.5f };
		std::vector<std::string> _personas;
		// personas.json: the owner's pins, runtime form id (reference or base NPC) -> persona.
		std::unordered_map<std::uint32_t, std::string> _overrides;
		std::vector<Line>        _lines;
		std::optional<Reply>     _reply;

		// The last line each (persona, scenario, role) played, so the same scene
		// type twice in a row does not open on the same sentence.
		std::unordered_map<std::string, std::string> _lastPicked;
		std::mt19937                                 _rng{ std::random_device{}() };
	};
}
