#pragma once

#include "NamedLock.h"

namespace RP
{
	// Scene barks (R-9): when a scene starts, the two people in it say something
	// that fits the decision that produced it.
	//
	// This class only CHOOSES. The line is spoken by the bridge, which receives a
	// kSayTopic order and calls Say on the Papyrus side -- the plugin never calls
	// into the VM (rule 1). The table it chooses from is generated by
	// scripts/build-barks-table.py from the same bank that numbers the ESP, so a
	// line picked here is a Topic the plugin actually has.
	//
	// Who speaks when: the initiator on "scene started", the responder a beat
	// later so the two lines do not play over each other. Observers are R-12 and
	// are not here yet.
	class Barks
	{
	public:
		[[nodiscard]] static Barks& GetSingleton() noexcept;

		void Load();

		// Below PapyrusLink's stale-start guard, so a late AAF event for a released
		// request can never make somebody speak for a scene that is not theirs.
		void OnSceneStarted(
			std::int32_t a_request, std::uint32_t a_initiator, std::uint32_t a_responder,
			std::string_view a_scenario);

		// Every way a scene ends. A reply still waiting belongs to a scene that is
		// gone, and speaking it would be a line about nothing.
		void OnSceneEnded();

		// Every poll. Releases the responder's line once it is due.
		void Pump();

		// R-7: derived from the form id, never stored. The same NPC is the same
		// persona forever, on every machine, at zero save cost.
		[[nodiscard]] std::string_view PersonaOf(std::uint32_t a_formID) const;

	private:
		struct Line
		{
			std::string   id;
			std::string   persona;
			std::string   scenario;
			std::string   role;
			char          gender{ 0 };   // 'm', 'f', or 0 for either
			std::uint32_t topic{ 0 };    // FILE-RELATIVE; the bridge adds the load order
		};

		struct Reply
		{
			std::int32_t                          request{ 0 };
			std::uint32_t                         speaker{ 0 };
			std::uint32_t                         target{ 0 };
			std::uint32_t                         topic{ 0 };
			std::string                           id;
			std::chrono::steady_clock::time_point due{};
		};

		// Null when nothing fits -- which the generator's coverage check says
		// cannot happen for a known scenario, and which is logged if it does.
		[[nodiscard]] const Line* Pick(
			std::string_view a_persona, std::string_view a_scenario, std::string_view a_role,
			std::int32_t a_sex);

		static void Say(std::uint32_t a_speaker, std::uint32_t a_target, std::uint32_t a_topic);

		mutable std::timed_mutex _lock;
		bool                     _enabled{ false };
		float                    _responderDelay{ 4.5f };
		std::vector<std::string> _personas;
		std::vector<Line>        _lines;
		std::optional<Reply>     _reply;

		// The last line each (persona, scenario, role) played, so the same scene
		// type twice in a row does not open on the same sentence.
		std::unordered_map<std::string, std::string> _lastPicked;
		std::mt19937                                 _rng{ std::random_device{}() };
	};
}
