#pragma once

namespace RP
{
	// Scene moans (R-29; roadmap item 3, with fo4-anatomy A-67).
	//
	// Anatomy's engine, with Rapport's "Anatomy's sex sounds" switch on ('RFAU'), mutes the packs'
	// own scene sounds, plays the body sounds itself, and tells Rapport what each partner's body is
	// doing ('RFAE' v1/v2 from "OCBPC plugin"): penetration began, a thrust at the deepest point (with
	// the stroke's length in ms, v2), a hard impact, ended. Rapport answers with a VOICE: an SNDR of
	// its own (Rapport.esp, tools/make_esp.py) played at the actor's head through Anatomy ('RFAP',
	// hello bit 12), because a Papyrus Say lands on the 3-second poll and could never hit a thrust.
	//
	// Which sound: the CHARACTER is sex x persona (Barks::PersonaOf) -- never the voice type, the owner:
	// "voices of humans jumping between octavas". The KIND follows the event:
	//   began / ended  -> a breath
	//   thrust         -> a moan whose LENGTH follows the tempo (owner: "faster -> shorter"): a
	//                     stroke under 600 ms takes a short one, under 1200 ms a medium, slower a long
	//   hard impact    -> a gasp, cutting whatever is playing
	//   AAF's climax tag on the playing animation -> the climax super moan, once per scene, cutting
	// Round 3 (owner, 2026-10-01): while the playing animation is anal, rough, aggressive or BDSM, the
	// moans and the gasp come from the PAINFUL-PLEASURE set; and the mouth's owner GAGS on a deep oral
	// stroke (RFAE: kind 5 "deep", or v3 flags bit 1), and is never given a moan while the mouth is full
	// (v3 flags bit 0, oral).
	// One voice at a time per actor: the next waits for the last to end (its take's length, from
	// moans.json) plus a short breath of quiet, so a scene breathes instead of droning.
	//
	// THREADS. RFAE arrives on whatever thread Anatomy dispatches from, so OnEvent reads NO game
	// state: who each actor is (sex x persona) is worked out on the main thread when their scene
	// starts (Register, from the bridge's natives), and every SNDR is resolved at Load. OnEvent only
	// looks those up, under one lock, and sends RFAP AFTER releasing it -- a listener that answered
	// on the same thread could otherwise re-enter and deadlock. It never touches the Papyrus VM.
	class Moans
	{
	public:
		[[nodiscard]] static Moans& GetSingleton() noexcept;

		// moans.json (generated by tools/make_esp.py), and every SNDR resolved. Main thread, at
		// data-ready, when Rapport.esp is loaded. No file, no moans.
		void Load();

		// From AnatomyHandler: one 'RFAE' message, raw. Any size it does not know is ignored.
		void OnEvent(const void* a_data, std::uint32_t a_length);

		// Main thread: these actors are in an AAF scene; learn who they are (sex x persona).
		void Register(const std::vector<std::uint32_t>& a_actors);

		// Rapport's own scene: who is in it, so its tags (which arrive without actors) can climax.
		void OwnSceneStarted(std::uint32_t a_first, std::uint32_t a_second);
		void OwnSceneEnded(std::uint32_t a_first, std::uint32_t a_second);
		// An animation's tags: on a climax tag, each actor's climax moan, once per scene.
		// The position our own scene plays now: AAF sends it just before its tags (Bridge.psc).
		void OwnScenePosition(std::string_view a_position);
		void OwnSceneTags(std::string_view a_tags);
		void SceneTags(const std::vector<std::uint32_t>& a_actors, std::string_view a_position, std::string_view a_tags);
		void SceneEnded(const std::vector<std::uint32_t>& a_actors);

		// A load: nobody is mid-moan in the world being left.
		void Reset();

		// From the bridge's pump, every poll, on the main thread: learn who any actor that sent a body
		// event before its scene registered is (or after a load), and play an "ended" breath that was
		// held back to see whether contact resumed.
		void Pump();

		// Their persona changed (the player's hotkey): the voice cached for them is re-learnt.
		void ForgetWho(std::uint32_t a_actor);

	private:
		enum class Kind : std::uint8_t
		{
			kBreath, kShort, kMedium, kLong, kImpact, kClimax,
			kPainShort, kPainMedium, kPainLong, kPainImpact, kGag,
			kCount
		};

		struct Sound
		{
			std::uint32_t local{ 0 };       // the SNDR's id in Rapport.esp
			std::uint32_t form{ 0 };        // resolved runtime id, 0 if it did not resolve
			float         longest{ 0.0f };  // the longest take: one plays at random
		};
		struct Actor
		{
			std::string                           character;   // "female_romantic"; empty = unknown
			std::chrono::steady_clock::time_point quietUntil{};
			std::chrono::steady_clock::time_point lastImpact{};
			std::chrono::steady_clock::time_point lastGag{};
			std::chrono::steady_clock::time_point climaxAt{};      // the last climax that PLAYED
			std::chrono::steady_clock::time_point climaxUntil{};   // ...and when it ends
			std::chrono::steady_clock::time_point breathAt{};      // a held "ended" breath, due then
			bool                                  climaxed{ false };
			bool                                  rough{ false };       // the playing animation's tags
			bool                                  mouthBusy{ false };   // a shaft or a lick in their mouth now
		};
		struct Message
		{
			std::uint32_t version{ 1 };
			std::uint32_t formID{ 0 };
			std::uint32_t soundFormID{ 0 };
			float         volume{ 1.0f };
			std::uint32_t flags{ 0 };
		};

		// Under _lock: picks the sound and arms the quiet. Returns the RFAP to send, or nullopt.
		[[nodiscard]] std::optional<Message> Pick(std::uint32_t a_actor, Kind a_kind, bool a_cut, std::string_view a_why);
		[[nodiscard]] std::optional<Message> Climax(std::uint32_t a_actor);
		static void                          Send(const std::vector<Message>& a_out);
		void                                 ResolveForms();
		[[nodiscard]] static bool            ClimaxTag(std::string_view a_tags);
		[[nodiscard]] static bool            RoughTag(std::string_view a_tags);
		void                                 NoteRough(const std::vector<std::uint32_t>& a_actors, bool a_rough);

		std::mutex                                             _lock;
		std::unordered_map<std::string, std::array<Sound, static_cast<std::size_t>(Kind::kCount)>> _characters;
		std::unordered_map<std::uint32_t, Actor>               _actors;
		std::uint32_t                                          _ownFirst{ 0 };
		std::uint32_t                                          _ownSecond{ 0 };
		std::string                                            _ownPosition;
		std::uint64_t                                          _played{ 0 };
		bool                                                   _loaded{ false };
		bool                                                   _saidNoPeer{ false };
		bool                                                   _saidUnknown{ false };
		// Diagnostics (owner's second test heard nothing and the log could not say why): what arrived,
		// what was sent, and why the rest was not -- a summary line every kSummaryEvery events.
		std::uint64_t _received{ 0 };
		bool          _saidBadEvent{ false };
		std::vector<std::uint32_t> _unknown;   // actors to learn on the next Pump
		std::uint64_t _skipNotLoaded{ 0 }, _skipBusy{ 0 }, _skipMouth{ 0 }, _skipNoPeer{ 0 }, _skipUnknown{ 0 },
			_skipNoSound{ 0 };
		void          Summary(std::string_view a_when);
		std::mt19937                                           _rng{ std::random_device{}() };
	};
}
